user_name = input( "Enter your name:" )
print(user_name. capitalize()) 

user_surname = input ( " Enter your surname:" )
print(list(user_surname))

user_age = input( "Enter your age:" )
result = 2023 - int(user_age)
print(result)

print(int(user_age) < 15 )
print(int(user_age) > 15 )
print(int(user_age) <= 15 )
print(int(user_age) >= 15 )
print(int(user_age) ==15 )
print(int(user_age) < 23 )
print(int(user_age) > 23 )
print(int(user_age) > 23 )
print(int(user_age) <= 23 )
print(int(user_age) >= 23 )
print(int(user_age) == 23 )
print(int(user_age) < 13 )
print(int(user_age) > 13 )
print(int(user_age) <= 13 )
print(int(user_age) >= 13 )
print(int(user_age) == 13 )